### Create client
POST http://localhost:3000/clients
Content-Type: application/json

{
	"firstName": "Manuel",
	"middleName": "Antonio",
	"firstSurname": "García",
	"email": "manu@gmail.com",
	"address": "25 Villas Agrícolas, Santo Domingo",
	"phone": "8094678512",
	"country": "DO"
}

### Get all clients
GET http://localhost:3000/clients?page=1&limit=10

### Get clients by country
GET http://localhost:3000/clients?country=US&page=1&limit=10

### Get client by id
GET http://localhost:3000/clients/a1d24fa8-0227-4fc7-9d63-36fae8430e7b

### Update client
PUT http://localhost:3000/clients/a1d24fa8-0227-4fc7-9d63-36fae8430e7b
Content-Type: application/json

{
	"email": "hernan@gmail.com",
	"address": "24 0404 Santo Domingo",
	"phone": "8294635157",
	"country": "US"
}

### Delete client
DELETE http://localhost:3000/clients/0496778b-b372-4c63-bef9-9965be82ccf5
